version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: shop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shop_cash_flow_manager
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - shop-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  app:
    build: .
    container_name: shop-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shop_cash_flow_manager?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: shop_user
      SPRING_DATASOURCE_PASSWORD: shop_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      
      # JPA Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      
      # Server Configuration
      SERVER_PORT: 8080
      SERVER_SERVLET_CONTEXT_PATH: /api
      
      # JWT Configuration
      JWT_SECRET: your-super-secret-jwt-key-here-make-it-at-least-32-characters-long-for-security
      JWT_EXPIRATION: 604800000
      
      # Logging Configuration
      LOGGING_LEVEL_COM_SHOP: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: WARN
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: WARN
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - shop-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/swagger-ui.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  shop-network:
    driver: bridge 